# This toolchain file was generated by Gradle to support NDK versions r14 and below.
include(/Users/mayikang/Library/Android/android-ndk-r14b/build/cmake/android.toolchain.cmake)
set(CMAKE_SYSTEM_VERSION 1)
